#!/bin/bash

CD_UNION_ARGS=()
CD_EMERGE_ARGS=()
CD_WRAPPER_ARGS=()

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      --)
      shift;
      while (( ${#@} )); do
        CD_EMERGE_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_EMERGE_ARGS+=(${1})
      ;;
    esac
    shift
  done

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  exit 1
fi

export CD_UNION_DIR=${CD_TMP_DIR}/union-${CD_TARGET}
export CD_WRAPPER_DIR=${CD_TMP_DIR}/wrapper-${CD_TARGET}

if [ -f "${CD_CONFIG_DIR}/crossdev-emerge-pre" ]; then
  ebegin "Executing crossdev emerge pre hook"
  source "${CD_CONFIG_DIR}/crossdev-emerge-pre" || cd_die
  eend 0
fi

if portageq envvar FEATURES | grep -q "distcc"; then
  einfo "Using distcc for emerge"
  CD_WRAPPER_ARGS+=(--cd-use-distcc)
fi

if [ ! -z "${CD_COW_ENV_CHROOT}" ]; then
  export FEATURES="-sandbox -usersandbox -userpriv ${FEATURES}"
fi

if ! cd_is_mount "${CD_UNION_DIR}"; then
ebegin "Creating union environment"
"${CD_SCRIPT_DIR}/crossdev-cow-env-init" "${CD_UNION_ARGS[@]}" || cd_die
eend 0
fi

ebegin "Creating wrapper environment"
"${CD_SCRIPT_DIR}/crossdev-wrapper-env-create" "${CD_WRAPPER_ARGS[@]}" || cd_die
eend 0

ebegin "Starting real emerge with: ${CD_EMERGE_ARGS[*]}"
cd_export_env_vars ${CD_TARGET} "${CD_TARGET_DIR}" "${CD_WRAPPER_DIR}"
${CD_TARGET}-emerge --config-root="${CD_TARGET_DIR}/" "${CD_EMERGE_ARGS[@]}" || cd_die
eend 0

if [ -f "${CD_CONFIG_DIR}/crossdev-emerge-post" ]; then
  ebegin "Executing crossdev emerge post hook"
  source "${CD_CONFIG_DIR}/crossdev-emerge-post" || cd_die
  eend 0
fi
