#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  exit 1
fi

if [ ! -f "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" ]; then
  eerror "First build ${CD_TARGET} kernel in \"${CD_TARGET_DIR}\" first, exiting"; exit 0
fi

if [ -d "${CD_TARGET_DIR}" ]; then
  
  ebegin "Installing RPi3 firmware in ${CD_TARGET_DIR}"

  if [ ! -d "${CD_TMP_DIR}/rpi-firmware" ]; then
    git clone --depth=1 https://github.com/raspberrypi/firmware.git "${CD_TMP_DIR}/rpi-firmware" || cd_die
  fi

  mkdir -p ${CD_TARGET_DIR}/boot
  cp -rav ${CD_TMP_DIR}/rpi-firmware/boot/* "${CD_TARGET_DIR}/boot/" || cd_die
  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" "${CD_TARGET_DIR}/boot/kernel8.img" || cd_die
  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b.dtb" "${CD_TARGET_DIR}/boot" || cd_die
  cp -av "${CD_TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b-plus.dtb" "${CD_TARGET_DIR}/boot" || cd_die

  eend 0

else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot install RPi3 firmware"
fi
