#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
ARCH=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="/usr/${TARGET}"
fi

if [ ! -f "${TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image" ]; then
  echo "Build ${TARGET} kernel in \"${TARGET_DIR}\" first, exiting"; exit 0
fi

if [ -d "${TARGET_DIR}" ]; then
  
  if [ ! -d "/tmp/rpi-firmware" ]; then
    git clone --depth=1 https://github.com/raspberrypi/firmware.git /tmp/rpi-firmware
  fi

  mkdir -p ${TARGET_DIR}/boot
  cp -rav /tmp/rpi-firmware/boot/* ${TARGET_DIR}/boot/
  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/Image ${TARGET_DIR}/boot/kernel8.img
  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b.dtb ${TARGET_DIR}/boot
  cp -av ${TARGET_DIR}/usr/src/linux/arch/arm64/boot/dts/broadcom/bcm2710-rpi-3-b-plus.dtb ${TARGET_DIR}/boot

fi
