#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      --)
      shift;
      while (( ${#@} )); do
        CD_ESELECT_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_ESELECT_ARGS+=(${1})
      ;;
    esac
    shift
  done

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  exit 1
fi

if [[ -f "${CD_CONFIG_DIR}/crossdev-eselect-pre" ]]; then
  ebegin "Executing crossdev eselect pre hook"
  source "${CD_CONFIG_DIR}/crossdev-eselect-pre" || cd_die
  eend 0
fi

ebegin "Starting real eselect with: ${CD_ESELECT_ARGS[*]}"
ROOT="${CD_TARGET_DIR}/" PORTAGE_CONFIGROOT="${CD_TARGET_DIR}/" eselect "${CD_ESELECT_ARGS[@]}" || cd_die
eend 0

if [[ -f "${CD_CONFIG_DIR}/crossdev-eselect-post" ]]; then
  ebegin "Executing crossdev eselect post hook"
  source "${CD_CONFIG_DIR}/crossdev-eselect-post" || cd_die
  eend 0
fi
