#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  exit 1
fi

if [ -d "${CD_TARGET_DIR}" ]; then

  if [[ -f "${CD_CONFIG_DIR}/crossdev-umount-pre" ]]; then
    ebegin "Executing crossdev umount pre hook"
    source "${CD_CONFIG_DIR}/crossdev-umount-pre" || cd_die
    eend 0
  fi

  if cd_is_mount "${CD_TARGET_DIR}/dev/pts"; then
    ebegin "Unmounting ${CD_TARGET_DIR}/dev/pts"
    umount -R "${CD_TARGET_DIR}/dev/pts" || cd_die
    eend 0
  fi

  if cd_is_mount "${CD_TARGET_DIR}/proc"; then
    ebegin "Unmounting ${CD_TARGET_DIR}/proc"
    umount -R "${CD_TARGET_DIR}/proc" || cd_die
    eend 0
  fi

  if cd_is_mount "${CD_TARGET_DIR}/dev"; then
    ebegin "Unmounting ${CD_TARGET_DIR}/dev"
    umount -R "${CD_TARGET_DIR}/dev" || cd_die
    eend 0
  fi

  if cd_is_mount "${CD_TARGET_DIR}/sys"; then
    ebegin "Unmounting ${CD_TARGET_DIR}/sys"
    umount -R "${CD_TARGET_DIR}/sys" || cd_die
    eend 0
  fi

  if [[ -f "${CD_CONFIG_DIR}/crossdev-umount-post" ]]; then
    ebegin "Executing crossdev umount post hook"
    source "${CD_CONFIG_DIR}/crossdev-umount-post" || cd_die
    eend 0
  fi

else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot unmount"
fi
