#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
ARCH=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="/usr/${TARGET}"
fi

if [ -d "${TARGET_DIR}" ]; then

  cp -a /usr/bin/qemu-${ARCH} ${TARGET_DIR}/usr/bin/qemu-${ARCH}-real
  gcc -static ${SCRIPT_DIR}/crossdev-qemu-wrapper/qemu-wrapper-${TARGET}.c -O3 -s -o /tmp/qemu-wrapper-${TARGET}
  cp -a /tmp/qemu-wrapper-${TARGET} ${TARGET_DIR}/usr/bin/qemu-${ARCH}
  rm -f /tmp/qemu-wrapper-${TARGET}

fi
