#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="${TARGET_DIR}"
fi

${SCRIPT_DIR}/crossdev-create --kernel 4.19 --binutils 2.32-r1 --gcc 8.3.0-r1 $@
