#!/bin/bash

cd "${CD_START_DIR}"

. /etc/profile

export PS1="\[\033[01;33m\][${CD_TARGET}] ${PS1}"

export PYTHONPATH="${CD_WRAPPER_PREFIX_DIR}/lib"
export PREROOTPATH="${CD_WRAPPER_PREFIX_DIR}/bin"
export PATH="${CD_WRAPPER_PREFIX_DIR}/bin:${PATH}"
export _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata

export CC="${CD_WRAPPER_PREFIX_DIR}/bin/${CD_TARGET}-gcc"
export CXX="${CD_WRAPPER_PREFIX_DIR}/bin/${CD_TARGET}-g++"
export CPP="${CD_WRAPPER_PREFIX_DIR}/bin/${CD_TARGET}-cpp"
