#!/bin/bash

CD_EXEC_ARGS=()

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      --)
      shift;
      while (( ${#@} )); do
        CD_EXEC_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_EXEC_ARGS+=(${1})
      ;;
    esac
    shift
  done

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  exit 1
fi

if [ -f "${CD_CONFIG_DIR}/crossdev-exec-pre" ]; then
  source "${CD_CONFIG_DIR}/crossdev-exec-pre" || cd_die
fi

ROOT="${CD_TARGET_DIR}/" SYSROOT="${CD_TARGET_DIR}/" PORTAGE_CONFIGROOT="${CD_TARGET_DIR}/" "${CD_EXEC_ARGS[@]}" || cd_die

if [ -f "${CD_CONFIG_DIR}/crossdev-exec-post" ]; then
  source "${CD_CONFIG_DIR}/crossdev-exec-post" || cd_die
fi
