#!/bin/bash

CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")

source "${CD_SCRIPT_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      --cd-qemu-arch)
      shift; CD_QEMU_ARCH=${1}
      ;;
    esac
    shift
  done

  if [[ ! -z "${CD_QEMU_ARCH}" ]]; then
    einfo "Using qemu arch: ${CD_QEMU_ARCH}";
  else
    eerror "No qemu arch specified, use --cd-qemu-arch";
    CD_HELP=1
  fi

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  echo "--cd-qemu-arch (Architecture part of user emulation binary)"
  exit 1
fi

if [ -d "${CD_TARGET_DIR}" ]; then
  if [ -f "/usr/bin/qemu-${CD_QEMU_ARCH}" ]; then
    if [ -f "${CD_CONFIG_DIR}/qemu-wrapper-${CD_TARGET}.c" ]; then
      CD_QEMU_WRAPPER_FILE="${CD_CONFIG_DIR}/qemu-wrapper-${CD_TARGET}.c"
    else
      CD_QEMU_WRAPPER_FILE="${CD_SCRIPT_DIR}/crossdev-qemu-wrapper/qemu-wrapper-${CD_TARGET}.c"
    fi
    if [ -f "${CD_QEMU_WRAPPER_FILE}" ]; then
        ebegin "Installing qemu user emulation in ${CD_TARGET_DIR} for ${CD_QEMU_ARCH} using a custom wrapper"
        cp -a "/usr/bin/qemu-${CD_QEMU_ARCH}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}-real" || cd_die
        gcc -static "${CD_QEMU_WRAPPER_FILE}" -O3 -s -o "/tmp/qemu-wrapper-${CD_TARGET}" || cd_die
        cp -a "/tmp/qemu-wrapper-${CD_TARGET}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}" || cd_die
        chmod 755 "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}" || cd_die
        rm -f "/tmp/qemu-wrapper-${CD_TARGET}" || cd_die
        eend 0
    else
        ebegin "Installing qemu user emulation in ${CD_TARGET_DIR} for ${CD_QEMU_ARCH} not using a custom wrapper"
        cp -a "/usr/bin/qemu-${CD_QEMU_ARCH}" "${CD_TARGET_DIR}/usr/bin/qemu-${CD_QEMU_ARCH}" || cd_die
        eend 0
    fi
  else
    eerror "No qemu user emulation binary for ${CD_TARGET} found, rebuild qemu with USE=\"qemu_user_targets_${CD_QEMU_ARCH}\""
  fi
else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot install qemu user emulation"
fi
