#!/bin/bash

CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")

source "${CD_SCRIPT_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  exit 1
fi

if [ -d "${CD_TARGET_DIR}" ]; then

  ebegin "Unmounting ${CD_TARGET_DIR}/dev/pts"
  cd_is_mount "${CD_TARGET_DIR}/dev/pts" && (umount -R "${CD_TARGET_DIR}/dev/pts" || cd_die)
  eend 0

  ebegin "Unmounting ${CD_TARGET_DIR}/proc"
  cd_is_mount "${CD_TARGET_DIR}/proc" && (umount -R "${CD_TARGET_DIR}/proc" || cd_die)
  eend 0

  ebegin "Unmounting ${CD_TARGET_DIR}/dev"
  cd_is_mount "${CD_TARGET_DIR}/dev" && (umount -R "${CD_TARGET_DIR}/dev" || cd_die)
  eend 0

  ebegin "Unmounting ${CD_TARGET_DIR}/sys"
  cd_is_mount "${CD_TARGET_DIR}/sys" && (umount -R "${CD_TARGET_DIR}/sys" || cd_die)
  eend 0

else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot unmount"
fi
