#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  exit 1
fi

if [ -d "${CD_TARGET_DIR}" ]; then

  if [ -f "${CD_CONFIG_DIR}/crossdev-mount-pre" ]; then
    ebegin "Executing crossdev mount pre hook"
    source "${CD_CONFIG_DIR}/crossdev-mount-pre" || cd_die
    eend 0
  fi

  if ! cd_is_mount "${CD_TARGET_DIR}/sys"; then
    ebegin "Mounting ${CD_TARGET_DIR}/sys"
    mkdir -pv "${CD_TARGET_DIR}/sys" || cd_die
    mount -v --bind /sys "${CD_TARGET_DIR}/sys" || cd_die
    eend 0
  fi

  if ! cd_is_mount "${CD_TARGET_DIR}/dev"; then
    ebegin "Mounting ${CD_TARGET_DIR}/dev"
    mkdir -pv "${CD_TARGET_DIR}/dev" || cd_die
    mount -v --bind /dev "${CD_TARGET_DIR}/dev" || cd_die
    eend 0
  fi

  if ! cd_is_mount "${CD_TARGET_DIR}/proc"; then
    ebegin "Mounting ${CD_TARGET_DIR}/proc"
    mkdir -pv "${CD_TARGET_DIR}/proc" || cd_die
    mount -v --bind /proc "${CD_TARGET_DIR}/proc" || cd_die
    eend 0
  fi

  if ! cd_is_mount "${CD_TARGET_DIR}/dev/pts"; then
    ebegin "Mounting ${CD_TARGET_DIR}/dev/pts"
    mkdir -pv "${CD_TARGET_DIR}/dev/pts" || cd_die
    mount -v --bind /dev/pts "${CD_TARGET_DIR}/dev/pts" || cd_die
    eend 0
  fi

  if [ -f "${CD_CONFIG_DIR}/crossdev-mount-post" ]; then
    ebegin "Executing crossdev mount post hook"
    source "${CD_CONFIG_DIR}/crossdev-mount-post" || cd_die
    eend 0
  fi

else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot mount"
fi
