#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="${TARGET_DIR}"
fi

CFLAGS="-O2 -pipe" CXXFLAGS="-O2 -pipe" PORTDIR_OVERLAY="" crossdev --target ${TARGET} $@

mv ${TARGET_DIR}/etc/portage ${TARGET_DIR}/etc/portage.$(date +%Y%m%d%H%M%S)
ln -fs ./lib ${TARGET_DIR}/usr/lib64
ln -fs ./lib ${TARGET_DIR}/lib64
mkdir -p ${TARGET_DIR}/usr/src/linux
mkdir -p ${TARGET_DIR}/etc/portage
mkdir -p ${TARGET_DIR}/packages
