#!/bin/bash

CD_COW_UNINIT_ARGS=()

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      *-cd-env-dir)
      shift; CD_ENV_DIR="${1}"
      ;;
      *-cd-env-dir=*)
      CD_ENV_DIR="${1#*=}"
      ;;
      --)
      shift;
      while (( ${#@} )); do
        CD_COW_UNINIT_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_COW_UNINIT_ARGS+=(${1})
      ;;
    esac
    shift
  done

  if [ -z "${CD_ENV_DIR}" ]; then
    export CD_ENV_DIR=${CD_TMP_DIR}/env-${CD_TARGET}
  fi

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  echo "--cd-env-dir <dir> (Environment dir) (${CD_ENV_DIR}}"
  exit 1
fi

export CD_ENV_COW_DIR=${CD_ENV_DIR}/cow-${CD_TARGET}
export CD_ENV_WORK_DIR=${CD_ENV_DIR}/work-${CD_TARGET}
export CD_ENV_UNION_DIR=${CD_ENV_DIR}/union-${CD_TARGET}
export CD_ENV_OVERLAY_DIR=${CD_ENV_DIR}/overlay-${CD_TARGET}

function unbind_wrapper_map_dir() {
  local dest=${1}
  if cd_is_mount "${CD_ENV_UNION_DIR}/${dest}"; then
    ebegin "Unbind map dir: ${dest}"
    umount ${CD_NODEBUG:--v} "${CD_ENV_UNION_DIR}/${dest}" || cd_die
    eend 0
  fi
}

function unbind_union_overlay_dir() {
  local dest=${1}
  if cd_is_mount_of_type "${CD_ENV_UNION_DIR}/${dest}" "overlay"; then
    ebegin "Unbind overlay dir: ${dest}"
    umount ${CD_NODEBUG:--v} "${CD_ENV_UNION_DIR}/${dest}" || cd_die
    eend 0
  fi
}

if [ -d ${CD_ENV_UNION_DIR} ]; then
  if cd_is_mount ${CD_ENV_UNION_DIR}; then

    ebegin "Unbinding host/target overlays"
    unbind_union_overlay_dir "/etc/portage"
    eend 0

    if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-pre" ]; then
      ebegin "Executing crossdev cow env uninit pre hook"
      source "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-pre" || cd_die
      eend 0
    fi

    ebegin "Uninitializing cow environment"

    ebegin "Killing all remaining processes"
    fuser -Mk ${CD_NODEBUG:--v} "${CD_ENV_UNION_DIR}"
    eend 0

    ebegin "Unbinding host/target mappings"
    unbind_wrapper_map_dir "/host" || cd_die
    unbind_wrapper_map_dir "${CD_TMP_DIR}" || cd_die
    unbind_wrapper_map_dir "$(cd_portageq "${CD_ENV_UNION_DIR}" envvar DISTDIR)" || cd_die
    unbind_wrapper_map_dir "$(cd_portageq "${CD_ENV_UNION_DIR}" envvar PORTAGE_TMPDIR)" || cd_die
    unbind_wrapper_map_dir "$(cd_portageq "${CD_ENV_UNION_DIR}" get_repo_path / gentoo)" || cd_die
    eend 0
    
    if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-unmount" ]; then
      ebegin "Executing crossdev cow env uninit unmount hook"
      source "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-unmount" || cd_die
      eend 0
    fi

    ebegin "Unmounting union filesystem"
    umount ${CD_NODEBUG:--v} -R "${CD_ENV_UNION_DIR}" || cd_die
    eend 0

    ebegin "Unmounting environment filesystem"
    umount ${CD_NODEBUG:--v} -R "${CD_ENV_DIR}" || cd_die
    eend 0

    eend 0

    if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-post" ]; then
      ebegin "Executing crossdev cow env uninit post hook"
      source "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-post" || cd_die
      eend 0
    fi

  else
    eerror "Cow environment not mounted, cannot uninitialize"
  fi
else
  eerror "Not a directory, cannot uninitialize"
fi
