#!/bin/bash

CD_ENV_ARGS=()
CD_COW_CHROOT_ARGS=()

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      *-cd-env-dir)
      shift; CD_ENV_DIR="${1}"
      ;;
      *-cd-env-dir=*)
      CD_ENV_DIR="${1#*=}"
      ;;
      --)
      shift;
      while (( ${#@} )); do
        CD_COW_CHROOT_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_COW_CHROOT_ARGS+=(${1})
      ;;
    esac
    shift
  done

  if [ -z "${CD_ENV_DIR}" ]; then
    export CD_ENV_DIR=${CD_TMP_DIR}/env-${CD_TARGET}
  fi

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  echo "--cd-env-dir <dir> (Environment dir) (${CD_ENV_DIR}}"
  exit 1
fi

if [ ! -e "${CD_TARGET}/${PWD}" ]; then
  export CD_CUR_DIR="/"
else
  export CD_CUR_DIR=${PWD}
fi

export CD_ENV_COW_DIR=${CD_ENV_DIR}/cow-${CD_TARGET}
export CD_ENV_WORK_DIR=${CD_ENV_DIR}/work-${CD_TARGET}
export CD_ENV_UNION_DIR=${CD_ENV_DIR}/union-${CD_TARGET}
export CD_ENV_OVERLAY_DIR=${CD_ENV_DIR}/overlay-${CD_TARGET}

if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" ]; then
  source "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" || cd_die
fi

if ! cd_is_mount "${CD_ENV_UNION_DIR}"; then
"${CD_SCRIPT_DIR}/crossdev-cow-env-init" "${CD_COW_CHROOT_ARGS[@]}" || cd_die
fi

if cd_is_mount "${CD_ENV_UNION_DIR}"; then
  CD_ENV_ARGS+=("-u ROOT")
  CD_ENV_ARGS+=("-u SYSROOT")
  CD_ENV_ARGS+=("-u CD_TARGET")
  CD_ENV_ARGS+=("-u CD_ENV_DIR")
  CD_ENV_ARGS+=("-u CD_CUR_DIR")
  CD_ENV_ARGS+=("-u CD_PREFIX_DIR")
  CD_ENV_ARGS+=("-u CD_TARGET_DIR")
  CD_ENV_ARGS+=("-u PORTAGE_CONFIGROOT")

  CD_ENV_ARGS+=("CD_CHROOT_ENV=1")
  CD_ENV_ARGS+=("CD_COW_ENV_CHROOT=1")
  
  if [ "${CD_HOST}" != "${CD_TARGET}" ]; then
    CD_ENV_ARGS+=("CD_HOST_DIR=/")
    CD_ENV_ARGS+=("CD_HOST=${CD_TARGET}")
  fi

  export SANDBOX_WRITE=${SANDBOX_WRITE}:${CD_ENV_DIR%/}

  if (( ${#CD_COW_CHROOT_ARGS[@]} )); then
    chroot "${CD_ENV_UNION_DIR}" /usr/bin/env ${CD_ENV_ARGS[@]} /bin/bash /profile "${CD_COW_CHROOT_ARGS[@]}" || cd_die
  else
    chroot "${CD_ENV_UNION_DIR}" /usr/bin/env ${CD_ENV_ARGS[@]} CD_COW_ENV_CHROOT_ENTER=1 /bin/bash --rcfile "/profile" || cd_die
  fi
else
  eerror "Union prefix dir ${CD_ENV_UNION_DIR} does not exist, cannot chroot"
fi

if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-post" ]; then
  source "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-post" || cd_die
fi
