#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="/usr/${TARGET}"
fi

${SCRIPT_DIR}/crossdev-emerge ${TARGET} ${TARGET_DIR} --ask --tree --usepkg-exclude="*" $@ sys-devel/gcc sys-devel/binutils
