#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
CONFIRM=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="${TARGET_DIR}"
fi

if [[ "${CONFIRM}" == "ICONFIRM" ]]; then
  echo "Confirmed clean"

  if [[ -f "${SCRIPT_DIR}/crossdev-clean-pre" ]]; then
    source "${SCRIPT_DIR}/crossdev-clean-pre"
  fi

  if mount | grep -q "${TARGET_DIR}"; then
    echo "Mounted filesystems in subirectories detected, exiting"; exit 0
  fi

  CFLAGS="-O2 -pipe" CXXFLAGS="-O2 -pipe" PORTDIR_OVERLAY="" crossdev -C --target ${TARGET}

  if [[ -f "${SCRIPT_DIR}/crossdev-clean-post" ]]; then
    source "${SCRIPT_DIR}/crossdev-clean-post"
  fi

else
  echo "Confirm with ICONFIRM as the 3th argument"
fi
