#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="/usr/${TARGET}"
fi

is_mount() {
  path=$(readlink -f $1)
  grep -q "$path" /proc/mounts
}

COW_PREFIX_DIR=/tmp/cow-${TARGET}
UNION_PREFIX_DIR=/tmp/union-${TARGET}

if [[ -f "${SCRIPT_DIR}/crossdev-cow-env-enter-pre" ]]; then
  source "${SCRIPT_DIR}/crossdev-cow-env-enter-pre"
fi

if is_mount "${UNION_PREFIX_DIR}"; then
  chroot ${UNION_PREFIX_DIR} /usr/bin/env -i TARGET="${TARGET}" COWHOME="${PWD}" HOME="${HOME}" TERM="${TERM}" PS1="${PS1}" /bin/bash --rcfile ${PWD}/crossdev-cow-env-bashrc
fi

if [[ -f "${SCRIPT_DIR}/crossdev-cow-env-enter-post" ]]; then
  source "${SCRIPT_DIR}/crossdev-cow-env-enter-post"
fi
