#!/bin/bash

CD_COW_UNINIT_ARGS=()

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      *-cd-chroot-dir)
      shift; CD_CHROOT_DIR="${1}"
      ;;
      *-cd-chroot-dir=*)
      CD_CHROOT_DIR="${1#*=}"
      ;;
      --)
      shift;
      while (( ${#@} )); do
        CD_COW_UNINIT_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_COW_UNINIT_ARGS+=(${1})
      ;;
    esac
    shift
  done

  if [ -z "${CD_CHROOT_DIR}" ]; then
    export CD_CHROOT_DIR=${CD_TMP_DIR}/chroot-${CD_TARGET}
  fi

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  echo "--cd-chroot-dir <dir> (Environment dir) (${CD_CHROOT_DIR}}"
  exit 1
fi

export CD_CHROOT_COW_DIR=${CD_CHROOT_DIR}/cow
export CD_CHROOT_WORK_DIR=${CD_CHROOT_DIR}/work
export CD_CHROOT_UNION_DIR=${CD_CHROOT_DIR}/union
export CD_CHROOT_OVERLAY_DIR=${CD_CHROOT_DIR}/overlay

function unmap_dir() {
  local name=${1} destination=${2}
  if [ -e "${CD_CHROOT_UNION_DIR}/${destination}" ]; then
    if cd_is_mount_of_type "${CD_CHROOT_UNION_DIR}/${destination}" "overlay"; then
      umount ${CD_NODEBUG:--v} "${CD_CHROOT_UNION_DIR}/${destination}" || cd_die
    fi
  fi
}

if [ -d ${CD_CHROOT_UNION_DIR} ]; then
  if cd_is_mount ${CD_CHROOT_UNION_DIR}; then

    if [ -f "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-pre" ]; then
      ebegin "Executing crossdev chroot env uninit pre hook"
      source "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-pre" || cd_die
      eend 0
    fi

    ebegin "Uninitializing chroot environment"

    ebegin "Killing all remaining processes"
    fuser -Mk ${CD_NODEBUG:--v} "${CD_CHROOT_UNION_DIR}"
    eend 0

    if [ -f "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-unmount" ]; then
      ebegin "Executing crossdev chroot env uninit unmount hook"
      source "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-unmount" || cd_die
      eend 0
    fi

    ebegin "Unmounting default filesystems"
    source "${CD_SCRIPT_DIR}/crossdev-umount" --cd-target-dir "${CD_CHROOT_UNION_DIR}" || cd_die
    eend 0

    ebegin "Unmounting union filesystem"
    umount ${CD_NODEBUG:--v} -R "${CD_CHROOT_UNION_DIR}" || cd_die
    eend 0

    ebegin "Unmounting environment filesystem"
    umount ${CD_NODEBUG:--v} -R "${CD_CHROOT_DIR}" || cd_die
    eend 0

    eend 0

    if [ -f "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-post" ]; then
      ebegin "Executing crossdev chroot env uninit post hook"
      source "${CD_CONFIG_DIR}/crossdev-chroot-env-uninit-post" || cd_die
      eend 0
    fi

  else
    eerror "Cow environment not mounted, cannot uninitialize"
  fi
else
  eerror "Not a directory, cannot uninitialize"
fi
