#!/bin/bash

CD_USE_LIBC="glibc"
CD_CROSSDEV_EMERGE_ARGS=()

CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")

source "${CD_SCRIPT_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

cd_parse_extra_arguments() {

  while (( ${#1} )); do
    case ${1} in
      --cd-use-rpi)
      CD_USE_RPI=1
      ;;
      --cd-use-musl)
      CD_USE_LIBC="musl"
      ;;
      --cd-use-glibc)
      CD_USE_LIBC="glibc"
      ;;
      --)
      shift;
      while (( ${#@} )); do
        CD_CROSSDEV_EMERGE_ARGS+=(${1})
        shift
      done
      break
      ;;
      *)
      CD_CROSSDEV_EMERGE_ARGS+=(${1})
      ;;
    esac
    shift
  done

}

cd_parse_extra_arguments "${CD_ARGS[@]}"

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  echo "--cd-use-rpi (Use RPi supported kernel)"
  echo "--cd-use-musl (Use musl as the libc)"
  echo "--cd-use-glibc (Use glibc as the libc)"
  exit 1
fi

if [[ "${CD_USE_LIBC}" == "musl" ]]; then
  einfo "Using musl";
  CD_CROSSDEV_EMERGE_ARGS+=("sys-libs/musl")
fi

if [[ "${CD_USE_LIBC}" == "glibc" ]]; then
  if [[ ! -z "${CD_LIBC_VER}" ]]; then
    einfo "Using glibc version: ${CD_LIBC_VER}";
  else
    CD_LIBC_VER=$(qatom -F '%{PVR}' $(qlist -Ive sys-libs/glibc))
    einfo "No glibc version specified, using: ${CD_LIBC_VER}";
  fi
  CD_CROSSDEV_EMERGE_ARGS+=("=sys-libs/glibc-${CD_LIBC_VER}")
fi

if [[ ! -z "${CD_KERNEL_VER}" ]]; then
  einfo "Using kernel version: ${CD_KERNEL_VER}";
else
  if [[ ! -z "${CD_USE_RPI}" ]]; then
    CD_KERNEL_VER="4.19"
    einfo "Using rpi kernel version: ${CD_KERNEL_VER}";
  else
    CD_KERNEL_VER=$(qatom -F '%{PVR}' $(qlist -Ive sys-kernel/linux-headers))
    einfo "No kernel version specified, using: ${CD_KERNEL_VER}";
  fi
fi
CD_CROSSDEV_EMERGE_ARGS+=("=sys-kernel/linux-headers-${CD_KERNEL_VER}")

if [[ ! -z "${CD_GCC_VER}" ]]; then
  einfo "Using gcc version: ${CD_GCC_VER}";
else
  CD_GCC_VER=$(qatom -F '%{PVR}' $(qfile -v $(realpath /usr/bin/gcc) | cut -d' ' -f1))
  einfo "No gcc version specified, using: ${CD_GCC_VER}";
fi
CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/gcc-${CD_GCC_VER}")

if [[ ! -z "${CD_BINUTILS_VER}" ]]; then
  einfo "Using binutils version: ${CD_BINUTILS_VER}";
else
  CD_BINUTILS_VER=$(qatom -F '%{PVR}' $(qfile -v $(realpath /usr/bin/ld) | cut -d' ' -f1))
  einfo "No binutils version specified, using: ${CD_BINUTILS_VER}";
fi
CD_CROSSDEV_EMERGE_ARGS+=("=sys-devel/binutils-${CD_BINUTILS_VER}")

if [[ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-pre" ]]; then
  ebegin "Executing crossdev bootstrap pre hook"
  source "${CD_CONFIG_DIR}/crossdev-bootstrap-pre" || cd_die
  eend 0
fi

ebegin "Writing package.mask to ${CD_TARGET_DIR}/etc/portage"
mkdir -p "${CD_TARGET_DIR}/etc/portage/package.mask/" || cd_die

cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/gcc"
>sys-devel/gcc-${CD_GCC_VER}
<sys-devel/gcc-${CD_GCC_VER}
EOF

if [[ "${CD_USE_LIBC}" == "glibc" ]]; then
cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/glibc"
>sys-libc/glibc-${CD_LIBC_VER}
<sys-libs/glibc-${CD_LIBC_VER}
EOF
fi

cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/binutils"
>sys-devel/binutils-${CD_BINUTILS_VER}
<sys-devel/binutils-${CD_BINUTILS_VER}
EOF

cat << EOF > "${CD_TARGET_DIR}/etc/portage/package.mask/linux-headers"
>sys-kernel/linux-headers-${CD_KERNEL_VER}
<sys-kernel/linux-headers-${CD_KERNEL_VER}
EOF
eend 0

ebegin "Starting crossdev emerge with: ${CD_CROSSDEV_EMERGE_ARGS[*]}"
export CD_TARGET CD_TARGET_DIR CD_CONFIG_DIR
${CD_SCRIPT_DIR}/crossdev-emerge --ask --tree --usepkg-exclude="*" "${CD_CROSSDEV_EMERGE_ARGS[@]}" || cd_die
eend 0

if [[ -f "${CD_CONFIG_DIR}/crossdev-bootstrap-post" ]]; then
  ebegin "Executing crossdev bootstrap post hook"
  source "${CD_CONFIG_DIR}/crossdev-bootstrap-post" || cd_die
  eend 0
fi
