#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  exit 1
fi

if [ -d "${CD_TARGET_DIR}" ]; then

  if [[ -f "${CD_CONFIG_DIR}/crossdev-mount-pre" ]]; then
    ebegin "Executing crossdev mount pre hook"
    source "${CD_CONFIG_DIR}/crossdev-mount-pre" || cd_die
    eend 0
  fi

  ebegin "Mounting ${CD_TARGET_DIR}/sys"
  mkdir -p "${CD_TARGET_DIR}/sys" || cd_die
  cd_is_mount "${CD_TARGET_DIR}/sys" || mount --bind /sys "${CD_TARGET_DIR}/sys" || cd_die
  eend 0

  ebegin "Mounting ${CD_TARGET_DIR}/dev"
  mkdir -p "${CD_TARGET_DIR}/dev" || cd_die
  cd_is_mount "${CD_TARGET_DIR}/dev" || mount --bind /dev "${CD_TARGET_DIR}/dev" || cd_die
  eend 0

  ebegin "Mounting ${CD_TARGET_DIR}/proc"
  mkdir -p "${CD_TARGET_DIR}/proc" || cd_die
  cd_is_mount "${CD_TARGET_DIR}/proc" || mount --bind /proc "${CD_TARGET_DIR}/proc" || cd_die
  eend 0

  ebegin "Mounting ${CD_TARGET_DIR}/dev/pts"
  mkdir -p "${CD_TARGET_DIR}/dev/pts" || cd_die
  cd_is_mount "${CD_TARGET_DIR}/dev/pts" || mount --bind /dev/pts "${CD_TARGET_DIR}/dev/pts" || cd_die
  eend 0

  if [[ -f "${CD_CONFIG_DIR}/crossdev-mount-post" ]]; then
    ebegin "Executing crossdev mount post hook"
    source "${CD_CONFIG_DIR}/crossdev-mount-post" || cd_die
    eend 0
  fi

else 
  eerror "Target dir ${CD_TARGET_DIR} does not exist, cannot mount"
fi
