#!/bin/bash

CD_SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]:-${0}}")
CD_SCRIPT_FILE=$(basename "${BASH_SOURCE[0]:-${0}}")

source "${CD_SCRIPT_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [[ ! -z "${CD_HELP}" ]]; then
  cd_print_usage_header
  exit 1
fi

CD_COW_PREFIX_DIR=${CD_TMP_DIR}/cow-${CD_TARGET}
CD_UNION_PREFIX_DIR=${CD_TMP_DIR}/union-${CD_TARGET}

mkdir -p "${CD_COW_PREFIX_DIR}"
mkdir -p "${CD_UNION_PREFIX_DIR}"

if [[ -d ${CD_UNION_PREFIX_DIR} ]]; then
  if cd_is_mount ${CD_UNION_PREFIX_DIR}; then
    if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-pre" ]]; then
      ebegin "Executing crossdev cow env uninit pre hook"
      source "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-pre" || cd_die
      eend 0
    fi

    ebegin "Uninitializing environment"

    ebegin "Killing all remaining processes"
    fuser -Mk "${CD_UNION_PREFIX_DIR}" || cd_die
    eend 0

    ebegin "Unmounting union"
    umount "${CD_UNION_PREFIX_DIR}" || cd_die
    eend 0

    eend 0

    if [[ -f "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-post" ]]; then
      ebegin "Executing crossdev cow env uninit post hook"
      source "${CD_CONFIG_DIR}/crossdev-cow-env-uninit-post" || cd_die
      eend 0
    fi
  fi
fi

