#!/bin/bash

CD_CUR_DIR=$(dirname "${BASH_SOURCE[0]}")

source "${CD_CUR_DIR}/crossdev-functions.sh"

cd_parse_arguments $@

if [ ! -z "${CD_HELP}" ]; then
  cd_print_usage_header
  exit 1
fi

export CD_COW_DIR=${CD_TMP_DIR}/cow-${CD_TARGET}
export CD_UNION_DIR=${CD_TMP_DIR}/union-${CD_TARGET}

export CD_WRAPPER_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}
export CD_WRAPPER_PREFIX_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}/usr
export CD_WRAPPER_INSTALL_DIR=${CD_TMP_DIR}/wrapper-cow-${CD_TARGET}/usr

if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-bashrc" ]; then
  CD_BASH_RC_FILE="${CD_CONFIG_DIR}/crossdev-cow-env-bashrc"
else
  CD_BASH_RC_FILE="$(dirname $(readlink -e ${CD_SCRIPT_FILE}))/crossdev-cow-env-bashrc"
fi

if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" ]; then
  source "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-pre" || cd_die
fi

if cd_is_mount "${CD_UNION_DIR}"; then
  if (( ${#CD_ARGS[@]} )); then
    chroot "${CD_UNION_DIR}" /usr/bin/env -C "${PWD}" "${CD_ARGS[@]}" || cd_die
  else
    chroot "${CD_UNION_DIR}" /usr/bin/env -C "${PWD}" /bin/bash --rcfile "${CD_BASH_RC_FILE}" || cd_die
  fi
  eend 0
else
  eerror "Union prefix dir ${CD_UNION_DIR} does not exist, cannot chroot"
fi

if [ -f "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-post" ]; then
  source "${CD_CONFIG_DIR}/crossdev-cow-env-chroot-post" || cd_die
fi
