#!/bin/bash

TARGET=$1
shift
TARGET_DIR=$1
shift
SCRIPT_DIR=$(dirname "$0")

if [[ -z "${TARGET_DIR}" ]]; then
  TARGET_DIR="${TARGET_DIR}"
fi

# Source: https://wiki.gentoo.org/wiki/Distcc/Cross-Compiling
LIBC_VER=$(qatom -F '%{PV}' $(qlist -Ive sys-libs/glibc))
KERNEL_VER=$(qatom -F '%{PV}' $(qlist -Ive sys-kernel/linux-headers))
GCC_VER=$(qatom -F '%{PV}' $(qfile -v $(realpath /usr/bin/gcc) | cut -d' ' -f1))
BINUTILS_VER=$(qatom -F '%{PV}' $(qfile -v $(realpath /usr/bin/ld) | cut -d' ' -f1))

${SCRIPT_DIR}/crossdev-create --kernel ${KERNEL_VER} --binutils ${BINUTILS_VER} --gcc ${GCC_VER} --libc ${LIBC_VER} $@
